SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60

# Fighter constants
FIGHTER_SPEED = 10
FIGHTER_START_X = SCREEN_WIDTH // 2
FIGHTER_START_Y = SCREEN_HEIGHT - 60

# Alien 등장 좌표
ALIEN_ROWS = 5
ALIEN_COLS = 12
ALIEN_START_X = 70
ALIEN_START_Y = 100
ALIEN_SPACING_X = 50
ALIEN_SPACING_Y = 70

BLACK = (0, 0, 0)